---
- name: Deploy the Lean Mean Media Machine
  hosts: homeservers
  become: true
  roles:
    - base
    - role: snapraid
      when: snapraid_parity_disks | length > 0
    - docker
    - media_stack
